# Generated by Django 3.0.4 on 2020-03-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição da peça')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço de entrega')),
                ('anunciante', models.CharField(max_length=50, verbose_name='Anunciante')),
                ('contato', models.CharField(max_length=100, verbose_name='Informações de contato')),
                ('status', models.ImageField(upload_to='', verbose_name='Status')),
            ],
        ),
    ]
