# Generated by Django 3.0.4 on 2020-03-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='descricao',
            field=models.TextField(max_length=300, verbose_name='Descrição da peça'),
        ),
    ]
