# Generated by Django 3.0.4 on 2020-03-11 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200311_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='endereco',
        ),
        migrations.AddField(
            model_name='demanda',
            name='bairro',
            field=models.CharField(blank=True, max_length=230),
        ),
        migrations.AddField(
            model_name='demanda',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='demanda',
            name='logradouro',
            field=models.CharField(blank=True, max_length=230),
        ),
        migrations.AddField(
            model_name='demanda',
            name='numero',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='anunciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='status',
            field=models.BooleanField(choices=[(False, 'Aberto'), (True, 'Finalizado')], default=False, max_length=1),
        ),
    ]
