# Generated by Django 3.0.4 on 2020-03-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200311_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='contato',
        ),
        migrations.AddField(
            model_name='demanda',
            name='email',
            field=models.EmailField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='demanda',
            name='telefone',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
