# Generated by Django 3.0.4 on 2020-03-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200311_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='descricao',
            field=models.TextField(max_length=500, verbose_name='Descrição da peça'),
        ),
    ]
